### ISSUE TITLE
"From the Archive" sidebar media pop-up does not work for non-OH AV materials

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/encyc-front#81]
When a "From the Archive" media item is a non-oral history audio-visual object, the AV player does not render in the lightview pop-up box as expected. This behavior pertains only to items that are dynamically populated in the "From the Archive" sidebar feature on the article detail page. The links in the FTA "more info" page function properly.

See: 

https://encyclopedia.densho.org/Japanese_associations/

**Comment by gjost** [comment]
fwiw on the old production site (encycfront-master-2.5.10, still visible at encycstage.densho.org) all these pop-up links return 403 errors.

**Comment by gjost** [comment]
These popups have never been media players; as long as we've had the popups they've displayed the thumbnails (see [ddr-object.html](https://github.com/densho/encyc-front/blob/master/front/wikiprox/templates/wikiprox/ddr-object.html)).  The [related-ddr.html](https://github.com/densho/encyc-front/blob/master/front/wikiprox/templates/wikiprox/related-ddr.html) page also just lists thumbnails.  The media playing happens over on the DDR site.

Are you asking to add DDR players to the Encyclopedia?

**Comment by gjost** [comment]
Apropos of not much, while investigating this I took a look at the Lightview pop-up js we're using. 
 Looks like it is no longer supported.  The Lightview link on [the author's personal site](https://www.nickstakenburg.com/) returns a 404.  Lightview does not appear among his repositories [on GitHub](https://github.com/staaky?tab=repositories). The `lightviewjs` [twitter account](https://twitter.com/lightviewjs) hasn't been updated since 2014.

**Comment by gjost** [comment]
Personally I've always thought the FTA thumbnails should be links to anchors for the corresponding items on the From the DDR page.

**Comment by GeoffFroh** [comment]
See https://github.com/denshoproject/encyc-front/issues/107
